### ISSUE TITLE
结构图是怎么画的？

### ISSUE THREAD

**Issue by magician-m** [YeexiaoZheng/Multimodal-Sentiment-Analysis#13]
![image](https://github.com/YeexiaoZheng/Multimodal-Sentiment-Analysis/assets/80674900/424b77e3-6b2b-424d-87e9-da81844057ec)
佬，又来麻烦你了~
我现在想要为模型画上结构图，看到你放的图，觉得蛮好，就像问下是怎么画的？我还想画更详细点。

**Comment by YeexiaoZheng** [comment]
PPT大法好！然后就是靠自己的双手成就你的梦想 PPT可操作性强 就是画得慢点
