### ISSUE TITLE
是一门课程里的吗，能提供一下来源课程吗

### ISSUE THREAD

**Issue by maolixiaolizi** [YeexiaoZheng/Multimodal-Sentiment-Analysis#16]
是一门课程里的吗，能提供一下来源课程吗

**Comment by YeexiaoZheng** [comment]
是我们ECNU本科人工智能课程的期末项目，在我们学校水杉平台上有课程：https://www.shuishan.net.cn/mooc/course/1507922820953452546

**Comment by maolixiaolizi** [comment]
> 是我们ECNU本科人工智能课程的期末项目，在我们学校水杉平台上有课程：https://www.shuishan.net.cn/mooc/course/1507922820953452546

非常感谢
