### ISSUE TITLE
你们使用的数据集叫啥名字？

### ISSUE THREAD

**Issue by wushibo750** [YeexiaoZheng/Multimodal-Sentiment-Analysis#2]

**Comment by YeexiaoZheng** [comment]
MVSA-Single 可在https://mcrlab.net/research/mvsa-sentiment-analysis-on-multi-view-social-data/ 下载原版数据，本实验数据标签经过改造，与原数据不同

**Comment by Kuaizr** [comment]
可以简单说一下做了什么改造吗？我看原始的数据text和image的标签有一些不是一样的

**Comment by YeexiaoZheng** [comment]
@Kuaizr 就相当于是重新人工标签过，因为原始数据集text和image是分别有一个标签的，而我们的数据集应该是老师他们重新标记过，text和image结合来给出一个标签，因为多模态最终是要把text和image结合来分析出一种情感，就像朋友圈的图片配文字表达的应该是同一种情感，所以改动就是这里。
