### ISSUE TITLE
您好，请问可以训练iemocap和meld数据集吗？

### ISSUE THREAD

**Issue by Haoyue-code** [YeexiaoZheng/Multimodal-Sentiment-Analysis#3]

**Comment by YeexiaoZheng** [comment]
看了一下这两个数据集是包含音频的，本项目不涉及音频，只有文本和图像的多模态情感分析。本项目整体结构还是挺简单的，你可以自行添加所需要的模态，项目内细节有什么问题还可以再问。

**Comment by Haoyue-code** [comment]
> 看了一下这两个数据集是包含音频的，本项目不涉及音频，只有文本和图像的多模态情感分析。本项目整体结构还是挺简单的，你可以自行添加所需要的模态，项目内细节有什么问题还可以再问。

谢谢，我的意思是如何用本项目训练那两个数据集中的文本和图像呢？

**Comment by YeexiaoZheng** [comment]
可以参考一下data文件夹内的文件格式，比如我这边的data/data里有1.txt, 1.jpg，只需要把那两个数据集的文本和图像按照这个格式去修改，然后在data中有train.txt，按照train.txt内的格式标记标签即可。或者你可以按你自己的需求修改common.py里读取文件的格式，然后在APIEncode.py里按照你的格式进行encode。
