### ISSUE TITLE
请问标签1的数据结果为什么都是0

### ISSUE THREAD

**Issue by Zhan9YC** [YeexiaoZheng/Multimodal-Sentiment-Analysis#6]
![image](https://github.com/YeexiaoZheng/Multimodal-Sentiment-Analysis/assets/102498073/36766e74-a6c4-4b98-9c97-6b729b1f5423)
是我的数据出问题了吗？还是代码？

**Comment by YeexiaoZheng** [comment]
你看看是否是预训练模型的问题？比如你数据是中文 模型用了英文的发自我的手机-------- 原始邮件 --------发件人： Zhan9YC ***@***.***>日期： 2023年9月18日周一 20:34收件人： YeexiaoZheng/Multimodal-Sentiment-Analysis ***@***.***>抄送： Subscribed ***@***.***>主    题： [YeexiaoZheng/Multimodal-Sentiment-Analysis] 请问标签1的数据结果为什么都是0 (Issue #6)

是我的数据出问题了吗？还是代码？

**Comment by CindyHX** [comment]
> ![image](https://private-user-images.githubusercontent.com/102498073/268644696-36766e74-a6c4-4b98-9c97-6b729b1f5423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzA4NTEsIm5iZiI6MTcxMjczMDU1MSwicGF0aCI6Ii8xMDI0OTgwNzMvMjY4NjQ0Njk2LTM2NzY2ZTc0LWE2YzQtNGI5OC05Yzk3LTZiNzI5YjFmNTQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNjI5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWU3ODhiNTllMmU5NDQwOTg0NjU0NDE3M2U4NmEzZTE1ZjNlNmViN2E1NDkyOWUxOTkzMDdiZDk4ZTU4MzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZpZluRpX0tfthXF4lfFj9ATwlrhRR53_8kyG3xo-MTM) 是我的数据出问题了吗？还是代码？

我在我的数据集上也是这样，我的数据集是英文数据集，请问你解决了嘛
