### ISSUE TITLE
请问可以用中文数据train 吗

### ISSUE THREAD

**Issue by adelina805105** [YeexiaoZheng/Multimodal-Sentiment-Analysis#7]
您好，我想用中文的数据集跑一下训练，请问除了bert的预训练模型之外，还有什么需要改的地方吗，非常需要您的建议与指导，谢谢！

**Comment by YeexiaoZheng** [comment]
可以的，应该只需要改BERT预训练模型，img用的是ImageNet那个预训练跑的应该是通用的

**Comment by adelina805105** [comment]
> 可以的，应该只需要改BERT预训练模型，img用的是ImageNet那个预训练跑的应该是通用的

我在config文件和 在执行命令中改用了bert-base-Chinese，出现了报错RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by adelina805105** [comment]
我这里的分类任务是4个类别，我想请教您，在config文件的参数设置里，loss_weight = [1.68, 9.3, 3.36]，这个loss_weight的数字是怎么得来的呢，我这里因为有4个类别，可能需要再加上一个数字吗

**Comment by YeexiaoZheng** [comment]
> > 可以的，应该只需要改BERT预训练模型，img用的是ImageNet那个预训练跑的应该是通用的
> 
> 我在config文件和 在执行命令中改用了bert-base-Chinese，出现了报错RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

这个应该是CUDA的error 不太清楚 现在我的英文的例子能跑通吗？

**Comment by YeexiaoZheng** [comment]
> 我这里的分类任务是4个类别，我想请教您，在config文件的参数设置里，loss_weight = [1.68, 9.3, 3.36]，这个loss_weight的数字是怎么得来的呢，我这里因为有4个类别，可能需要再加上一个数字吗

是需要加一个的，这是为了提高模型泛化能力的，比如类别A, B, C的样本数为a, b ,c，那么这个loss_weight[x, y, z]就是要保证a*x = b * y = c * z，四个类别同理

这个loss_weight好像只有一个model里用到了，NaiveCombineModel，lossfunc初始化用的

**Comment by adelina805105** [comment]
> > 我这里的分类任务是4个类别，我想请教您，在config文件的参数设置里，loss_weight = [1.68, 9.3, 3.36]，这个loss_weight的数字是怎么得来的呢，我这里因为有4个类别，可能需要再加上一个数字吗
> 
> 是需要加一个的，这是为了提高模型泛化能力的，比如类别A, B, C的样本数为a, b ,c，那么这个loss_weight[x, y, z]就是要保证a*x = b * y = c * z，四个类别同理
> 
> 这个loss_weight好像只有一个model里用到了，NaiveCombineModel，lossfunc初始化用的

okok! 非常感谢您！
