### ISSUE TITLE
您好，想咨询您一个报错

### ISSUE THREAD

**Issue by adelina805105** [YeexiaoZheng/Multimodal-Sentiment-Analysis#8]
<img width="836" alt="运行" src="https://github.com/YeexiaoZheng/Multimodal-Sentiment-Analysis/assets/77660706/3507c090-c5cc-41fc-b2a8-2f92ed4a1ecb">
您好，我在跑您的代码时，NavieCombine是可以跑通的，但其他的CMAC、OTE等模型全部报这个错误，我理解数据集应该没有问题，还请您指教，谢谢！

**Comment by YeexiaoZheng** [comment]
可能 torch版本不一样 输出的东西维度不一样 你可以看看text_feature和img_text_attention_out这两个东西分别是几维的 应该是需要两个维度（没记错的话 可以把维度转成需要的
