### ISSUE TITLE
关于数据集和融合方式的一些小问题

### ISSUE THREAD

**Issue by LXT2017** [YeexiaoZheng/Multimodal-Sentiment-Analysis#9]
您好，我想问一下找个数据集是自己爬取的还是公开数据集，另外几种融合方式是参考论文的还是自己想出来的，如果是有公开数据集或者参考的论文，可以发一下吗，非常感谢您

**Comment by YeexiaoZheng** [comment]
这个数据集是MVSA数据集，几种融合方式是看了一些论文，然后自己拍脑子想的，所以效果上可能不是很好，参考的论文就是reference里的
